#!/usr/bin/env python3

import sys
import os

def printUsage():
    print("USAGE...")

def storeFileContent(fd):
    for line in fd:
        print(line, end="")

def getArgs():
    if (len(sys.argv) < 2):
        sys.exit(84)
    elif (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        printUsage()
    else:
        if (os.path.isfile(sys.argv[1])):
            fd = open(sys.argv[1], "r")
            return(storeFileContent(fd))
        else:
            sys.exit(84)

getArgs()